/*
 * AUTHOR	Denise Nguyen
 * DATE 	10/26/2017
 * COURSE   	CIS444 
 * PURPOSE  	{s.dot} Database 
*/

/*
DROP TABLE USERS;
DROP TABLE PROJECTS;
DROP TABLE MEMBERS;
DROP TABLE TASKS;
DROP TABLE BUGS;
DROP TABLE FOURMS;
- Assign bugs or fix bugs 


*/

/*Bug Tracking Table*/
CREATE TABLE BUGS(
	Bugs_ID INT NOT NULL AUTO_INCREMENT,
	Sourcefile VARCHAR(25) NOT NULL,
	Location CHAR(15) NOT NULL,
	Description VARCHAR(50) NOT NULL,
	BugStauts VARCHAR(15) NOT NULL,
	BugReporter_ID VARCHAR(15) NOT NULL,
	BugAssigned_ID VARCHAR(15) NOT NULL,
);



