/*
 * AUTHOR	Denise Nguyen
 * DATE 	10/26/2017
 * COURSE   CIS444 
 * PURPOSE  {s.dot} Database 
*/

/*
DROP TABLE USERS;
DROP TABLE PROJECTS;
DROP TABLE MEMBERS;
DROP TABLE TASKS;
DROP TABLE BUGS;
DROP TABLE FOURMS;
- 

*/

/*Dev Fourm Table*/
CREATE TABLE FOURMS(
	Fourm_ID INT NOT NULL AUTO_INCREMENT,
	Comment VARCHAR(50) NOT NULL,
	
	/* FORUM USER ID FK
	FourmUser_ID VARCHAR(15) NOT NULL*/
);

